- name: Install FreeType engine with the patented subpixel rendering enabled
  dnf:
    name: freetype-freeworld
    state: latest
  become: true

- name: Copy font engine config
  copy:
    src: "{{ role_path }}/files/local.conf"
    dest: /etc/fonts/local.conf
  become: true

- name: Install multimedia codecs
  dnf: 
    name:
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-good-gtk
      - gstreamer1-plugins-good-qt
      - gstreamer1-plugins-base
      - gstreamer1-libav
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-bad-free-wildmidi
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-good-extras
      - lame
  become: true