- hostname:
    name: {{ host_name }}

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

#- name: Add Standard Notes desktop icon
#  copy:
#    src: "{{ role_path }}/files/standard-notes.desktop"
#    dest: /home/nduhovnijs/.local/share/applications/standard-notes.desktop
#  become: true

- name: Add a script for switching between Bluetooth profiles
  copy:
    src: "{{ role_path }}/files/bluetooth_profile.sh"
    dest: "{{ home_dir }}/bin/bluetooth_profile.sh"
    mode: 0755
  become: true